### ISSUE TITLE
Is possible to extend the support to Chromium browser?

### ISSUE THREAD

**Issue by effelle** [idolize/xcloud-keyboard-mouse#10]
HI, thanks for this extension, much appreciated.

I have a couple of old Notebook running [CloudReady](https://www.neverware.com/#intro) the official free version of ChromeOS. 
The OS is based on Chromium instead of Chrome and does not support Android's VM/framework nor has a stable Linux subsystem, then it's impossible to install another browser like Edge. 

On Chromium your extension icon is green all the time but the upper left switch is turned off. 
If I turn it on as soon as I close the settings window it will revert to its original state and `playing` always report `None` when I'm on game. Gamepad tester doesn't detect the virtual gamepad.

Could you gently have a look?

Thanks.  

F.

**Comment by idolize** [comment]
Hi @effelle I pushed a new version (1.3) with some changes (there was a regex that I realized wasn't supported on older browsers after testing in Safar). You can try updating and see if it works now.

Can you share what version of Chromium (not sure if Chromium has the same version numbers as Chrome) you are on? Do you know if it supports [Manifest v3](https://developer.chrome.com/docs/extensions/mv3/intro/) extensions or not?

One thing I've been meaning to do is find an easier way for users to report issues like this to include some debug output, since it's not obvious what is failing in your case.

**Comment by effelle** [comment]
Hi David!
I do apologize for the late reply but somehow I missed the notification.
I agree, a log would have been better to explain the issue, but luckily for us it's not needed anymore.
The latest update of Cloudready on stable-channel (94.4.4)  and using the latest version of your extension solved the issue. 
The problem is the device itself, since it has just a 2.4Ghz connection is not really suitable for cloud gaming but that's another story.
For the sake of knowledge, the version of Chromium installed with Cloudready is the 94.0.4606.126 (official) and it does indeed support Manifest V3 (since the V88 stable).

Cheers,

Federico
