### ISSUE TITLE
Get the free version back

### ISSUE THREAD

**Issue by therealtutugoy** [idolize/xcloud-keyboard-mouse#105]
I know you all want to make money but I have a project I need to do in fortnite and this is the only way I play. You making me pay just for an extension just terrible and evil. Please change this quick!!! And make the free version again!!! PLEASE!

**Comment by idolize** [comment]
Please don't say paying for an extension is "terrible and evil" because that is not true. I have the right to decide how much I charge for my time and work - nobody deserves to tell me to make things for them for free.

However, I am looking into regional pricing or other ways for people to play that can't afford the $3.99. Where are you located? Hopefully I can share something soon.

**Comment by therealtutugoy** [comment]
Sorry I can overreact sometimes with my words even in tech. I am located in the us and super sorry for criticizing you.

**Comment by idolize** [comment]
Sure, [check out Google's documentation](https://developer.chrome.com/docs/extensions/mv3/). It's done in JavaScript (or TypeScript) primarily.
