### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by meisme-dev** [idolize/xcloud-keyboard-mouse#27]
Title!

**Comment by idolize** [comment]
Thanks for the request. Firefox is [not an officially supported browser for xCloud](https://support.xbox.com/en-US/help/games-apps/cloud-gaming/supported_browsers), which is why I have not currently brought it to that browser. However, I have tried xCloud in Firefox and it does seem to work.

It should be fairly straightforward to port the extension to Firefox - the main hurdle is just the fact that Firefox does not currently support Manifest V3 extensions, although [they say they should start supporting it in "early 2022"](https://blog.mozilla.org/addons/2021/05/27/manifest-v3-update/). I have already partially back-ported support for Manifest V2 as I added support for Safari, but I will need to polyfill all the promise-based calls as well.

No ETA on when this will be available, but I'll keep it open until I get some time to add this (or who knows, maybe Firefox will ship Manifest V3 soon in which case it will be trivial to support!).

**Comment by theAntiBob** [comment]
Firefox support would be very much appreciated...
xbox.com/play through chromium tells me my controller is disconnected, my network is unsupported and that my browser is supported. continue anyway only renders a black screen. no audio even if the audio indicator on the tab plays
xbox.com/play through firefox tells me that the controller is connected, the network is supported and the browser is unsupported. continue anyway renders video and plays aduio just fine, but the controller doesn't function at all.

**Comment by BibliaAberta** [comment]
Up

**Comment by barfin** [comment]
I want this too
i know firefox is not officially supported by microsoft but xcloud works fine for me with firefox on linux without user-agent switcher

**Comment by Zormein** [comment]
Firefox works perfectly fine for me this feature should definitely be added. If not officially could someone tell me how to build it?

**Comment by idolize** [comment]
@Zormein @barfin @BibliaAberta @theAntiBob @meisme-dev Now that Firefox v109 supports Manifest v3 I have published the extension to the Firefox Add-Ons store! https://addons.mozilla.org/en-US/firefox/addon/keyboard-mouse-for-xbox-xcloud/
