### ISSUE TITLE
It only works in English!

### ISSUE THREAD

**Issue by joaochris** [idolize/xcloud-keyboard-mouse#3]
Congratulations on the initiative and the project! Unfortunately it only works on xcloud in English. Will it bring support for other languages ​​as well, such as Brazilian Portuguese which is mine?

**Comment by KaMyKaSii** [comment]
Same issue, just work with the "en-US" site variant.

**Comment by idolize** [comment]
I've submitted a new version (v1.1) to the Chrome Web Store which should enable the extension on all locale pages of xcloud now (not just en-us).

Let me know if it works for you!

**Comment by AlcatrazCrysis2** [comment]
@idolize it doesn't for pl-PL still.

**Comment by joaochris** [comment]
@idolize I tested it here and it still doesn't work :(

**Comment by KaMyKaSii** [comment]
> I've submitted a new version (v1.1) to the Chrome Web Store which should enable the extension on all locale pages of xcloud now (not just en-us).
> 
> Let me know if it works for you!



> I've submitted a new version (v1.1) to the Chrome Web Store which should enable the extension on all locale pages of xcloud now (not just en-us).
> 
> Let me know if it works for you!

My experience is that it doesn't work when you open the https://www.xbox.com/pt-BR/play site and then click on a game from the catalog. But it works if after opening the game, you refresh the page. Maybe the xbox site uses that loading method inside the site itself (like on YouTube) and then the extension can't see the URL change? I believe that if you change the pattern to "https://www.xbox.com/*/play*" without the slash at the end it would work in all cases, but then the home page of the catalog would also be included, in which case it would be necessary to decrease the mouse warning on the screen and move it to a non-intrusive area

**Comment by joaochris** [comment]
@KaMyKaSii That's really what you said!

**Comment by AlcatrazCrysis2** [comment]
@KaMyKaSii it worked now, thanks

**Comment by idolize** [comment]
Oh that's good info to understand! I'll take a look at the initialization logic and make sure it loads correctly when coming from the root xCloud/Xbox page (I was testing by just going directly to a game URL)

**Comment by KaMyKaSii** [comment]
> Oh that's good info to understand! I'll take a look at the initialization logic and make sure it loads correctly when coming from the root xCloud/Xbox page (I was testing by just going directly to a game URL)

I just tested and using the pattern `"*://*.xbox.com/*/play*"` works as expected. Do not load on the home catalog page but loads after open some game.

**Comment by idolize** [comment]
@KaMyKaSii thanks for the heads up! Turns out Typeform has a limit of 10 responses in their free plan which I didn't realize when I made it, so I'm going to switch to Google Forms.

And I'll definitely take another look at how to make sure everything loads correctly regardless of how you get to the game page.

For now, I recommend refreshing the page when you get to the game you want to play.

**Comment by idolize** [comment]
@KaMyKaSii @joaochris @AlcatrazCrysis2 Heads up I submitted a version `1.2` for review - pending right now - which should address these issues.

**Comment by KaMyKaSii** [comment]
> @KaMyKaSii @joaochris @AlcatrazCrysis2 Heads up I submitted a version `1.2` for review - pending right now - which should address these issues.

Working good know, thanks!

Off topic, do you believe there are still optimizations for converting mouse to analog to have more precise movements or that what you could do has already been done? On the gamepad-tester the analog output seems "crazy" despite being making a movement at almost constant speed and direction

**Comment by idolize** [comment]
@KaMyKaSii great, glad it's working!

If you turn down the sensitivity control on your preset then the analog stick movement in gamepad-tester will seem smoother, but I've found it's a little too slow to use in actual gameplay like that.

Basically, [there's some math that calculates how far your mouse moved between frames](https://github.com/idolize/xcloud-keyboard-mouse/blob/master/src/browser/browserEventProcessor.ts#L47-L57), and then sets the axis location of the joystick based on that. If your mouse only moves one or two pixels in a frame, then we could set the joystick to only be a light movement in that direction vs. your mouse moves 20, 30, or 100+ pixels between frames because you swiped it across your mousepad super fast then the most we can do is set the joystick to be fully maxed out in that direction.

But if you think about how a game engine processes joystick input vs mouse input it's different, because joystick input is merely a signal saying "start moving me (or the camera) in this direction, until I stop holding the stick" while mouse camera movement is more like "literally shift the camera X and Y pixels instantly as the mouse moves and then stop"

I think one way to improve this would be to lower the sensitivity some in the extension settings, but increase the sensitivity in the game settings (and make sure there is zero "dead zones" in the game options).

Open to feedback or PRs though if you want to try playing with it yourself.

**Comment by idolize** [comment]
Closing because the main issue (URL matching only working for `/en-US/`) has been fixed!
