### ISSUE TITLE
Extreme input lag

### ISSUE THREAD

**Issue by Cjanzen-1** [idolize/xcloud-keyboard-mouse#30]
When I am playing with the emulator I have ~250-500 ms of lag from when I move my mouse or press a key to when the action happens. I have a gigabit connection with low latency, so I don't think my connection is the issue.

**Comment by idolize** [comment]
This isn't caused by the extension - the extension merely [sets a global state in the javascript](https://github.com/idolize/xcloud-keyboard-mouse/blob/master/src/browser/gamepadSimulator.ts#L127) whenever you press a button - so this should be nearly instant - and if you are using a wired keyboard it should be even faster than a wireless controller!

You can try turning off the extension (or even uninstalling it) and see if you still have the latency.

---

One thing that sometimes gets mistaken for latency, however, is the mouse movement feeling "sluggish" when you move the camera in game etc. This is because the mouse simulates moving a virtual analog stick, so a quick mouse movement (usually instant camera move in PC games) can only correspond to tilting the stick (which takes some time to move the camera via a controller).

One thing you can do to improve this is to increase the controller stick sensitivity in the in-game settings.
