### ISSUE TITLE
[Feature Request] Move 'click-to-enable-mouse-xmc' element under xCloud's menu if it is present

### ISSUE THREAD

**Issue by FlaminSarge** [idolize/xcloud-keyboard-mouse#4]
xCloud's menu is made up of a containing div with class `Menu-module__scrollable___2wUvo StreamMenu-module__menu___3Fqci` (or similar) with a series of divs under it for buttons, e.g. `<div role="button" tabindex="0" class="MenuItem-module__container___Zp_VD Menu-module__menuItem___11v6G StreamMenu-module__menuItem___1AqGY" aria-label="Muted" aria-pressed="false">...</div>`

While I'm not sure if it's viable, appending the click-to-enable-mouse-xmc div to this list and copying the styles of the other buttons would be a neat addition for managing analog mouse through the xCloud native menu instead of a prompt that sits in the center of the screen.

**Comment by idolize** [comment]
Hey @FlaminSarge that's an interesting idea. It is technically possible for sure, although I'm a little hesitant to couple the code too tightly to specific page elements (especially since the IDs/classes in the DOM appear to use generated hashes in the suffix). Any update Microsoft makes to their UI could break it.

But maybe I can find a way to insert an item without using such specific IDs, or even just add a better way to show/dismiss the cursor click prompt so it's less intrusive.

**Comment by idolize** [comment]
Hi @FlaminSarge I submitted a version `1.2` for review which moves the mouse click notice up towards the top of the screen so it should obstruct the xcloud menu less. Hopefully for now that makes it easier, but I'll continue looking into better ways to hide it, especially when you move back and forth between the game select screen and an active game session.

**Comment by FlaminSarge** [comment]
Another related option is to allow disabling the prompt for mouse input if another controller is already present. Ran into an issue where I was using an actual controller on xCloud and could not get the extension's prompt to go away until I disabled it, which I suppose is currently intended but is a bit awkward to navigate.

**Comment by idolize** [comment]
@FlaminSarge I just added another update which should do a better job of hiding the "Click to enable" UI whenever you aren't actively in a game (e.g. if you open a menu etc.)

That's an interesting idea about auto-disabling if there is another controller present - it should be possible to do, although I wonder if that would always be the desired behavior? I.e. what if someone always keeps a gamepad connected but they want to switch to mouse + keyboard?

**Comment by FlaminSarge** [comment]
Would it be possible to style/position the mouse prompt as a small mouse icon near the `...` and Xbox icons in the top right, only showing up when you hover near that area (in the same way those do)? In general the mouse analog is something I tend not to use in favor of just WASD + OKLsemicolon/etc., so it'd be useful to have the option to put the prompt somewhere entirely out of the way, while still accessible if needed.

**Comment by idolize** [comment]
@FlaminSarge I can add a "minimize" button to the larger "click to enable" UI? My only concern with making it too small is for new users who don't know they have to click that area in order to enable mouse capture (the clicking behavior is a browser requirement to enable pointer lock)...

It's also currently possible to just disable that area in your preset if you don't use it by selecting the "None" option for "which analog stick to control via the mouse":

<img width="370" alt="Screen Shot 2021-12-02 at 11 36 34 AM" src="https://user-images.githubusercontent.com/635005/144464054-f3c2797f-ae63-411c-abd8-9db1664a258d.png">

**Comment by idolize** [comment]
Hi @FlaminSarge I pushed an update (`2.3`) which now includes a "minimize/maximize" feature. Let me know what you think!

<img width="572" alt="Screen Shot 2021-12-09 at 1 16 18 PM" src="https://user-images.githubusercontent.com/635005/145452945-99949c6d-9a4d-4978-a139-707781ce1609.png">
<img width="536" alt="Screen Shot 2021-12-09 at 1 16 23 PM" src="https://user-images.githubusercontent.com/635005/145452947-f587fd43-7792-4994-8e13-3cbb3d3f088b.png">

**Comment by FlaminSarge** [comment]
This works well for my use case! It'd definitely be neat to try to include it within the stock Xbox buttons, but that'd be a followup change and definitely more for form than functionality.
